---
- hosts: all
  become: yes
  tasks:
    - name: Install packages
      yum:
        name: "{{item}}"
        state: present
      loop:
         - httpd
         - git
         - docker
         - telnet
